[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings=[
  "openzeppelin-contracts/=lib/openzeppelin-contracts/",
  "openzeppelin/=lib/openzeppelin-contracts/contracts/",
  "chainlink/=lib/chainlink/contracts/src/v0.8/",
]
[rpc_endpoints]
bsc_testnet = "${TESTNET_RPC_URL}"
[etherscan]
bsc_testnet = { key = "${BSCSCAN_API}", url="https://api-testnet.bscscan.com/", chain=97}

# See more config options https://github.com/foundry-rs/foundry/tree/master/config